### ISSUE TITLE
Fatal error, can't open config file '/usr/local/etc/redis/redis.conf': Permission denied

### ISSUE THREAD

**Issue by janusn** [redis/docker-library-redis#446]
Since updated to image tag '8.0.0', 'latest' or 'bookworm' the container cannot start with the following error logged:
```
 1:C 06 May 2025 16:14:37.089 # Fatal error, can't open config file '/usr/local/etc/redis/redis.conf': Permission denied
```
It runs fine with image tagged '7.4.3'

Environment:
Host:
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
compose.yaml:
```
---
services:
  redis:
    image: "redis:latest"
    container_name: nextcloud-redis
    deploy:
      resources:
        limits:
          memory: 128M
    command: /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - "./config:/usr/local/etc/redis"
      - "redis-data:/data"
    restart: unless-stopped
```
